# Generated by Django 4.1.6 on 2023-02-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_duration', models.IntegerField()),
                ('date_end', models.DateField()),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.IntegerField(primary_key=True, serialize=False)),
                ('name_role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('desk', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_duration', models.IntegerField()),
                ('date_end', models.DateField()),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task2Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_subtask', models.IntegerField()),
            ],
            options={
                'db_table': 'task2task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User2Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user2project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User2Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user2task',
                'managed': False,
            },
        ),
    ]
