# Generated by Django 4.1.6 on 2023-02-09 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user2task',
            options={'managed': True},
        ),
        migrations.CreateModel(
            name='delegate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_role', models.ForeignKey(db_column='id_role', on_delete=django.db.models.deletion.DO_NOTHING, to='task.role')),
                ('id_task', models.ForeignKey(db_column='id_task', on_delete=django.db.models.deletion.DO_NOTHING, to='task.task')),
            ],
        ),
    ]
